name: vitquant
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - nomkl
  - numpy=1.26
  - pillow
  - matplotlib
  - pytest
  - pip
  - pip:
      - torch
      - torchvision
      - timm
      - seaborn
      - pandas
      - huggingface_hub
      - datasets